version: '2'
services:
  ontonethub:
    build: ./src
    container_name: ontonethub-src
    depends_on:
      - tomcat
    entrypoint: /ontonethub-src/startup.sh
    volumes:
      - myshare:/usr/local/tomcat/webapps
  tomcat:
    image: tomcat
    ports:
     - 8000:8080
    environment:
     - CATALINA_OPTS=-Xmx1g -Xms1g -XX:MaxPermSize=1024m
    volumes:
      - myshare:/usr/local/tomcat/webapps
volumes:
  myshare:
    driver: local      
     
     
